######################################################################
# Automatically generated by qmake (2.01a) dim. mai 6 14:40:11 2007
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += release console
DESTDIR = ./

QT += network

# Input
HEADERS = Notifier.h Teeworlds.h
SOURCES = Notifier.cpp main.cpp Teeworlds.cpp
